backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/images/uploads"
public_folder: "/assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "---"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date", format: 'YYYY-MM-DD' }
      - { label: "updated", name: "updated", widget: "date", format: 'YYYY-MM-DD', required: false}
      - { label: "intro", name: "intro", widget: "string" }
      - { label: "canonical", name: "canonical", widget: "string", required: false }
      - { label: "publication", name: "publication", widget: "string", required: false }
      - { label: "permalink", name: "permalink", widget: "string" }
      - { label: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: fr